---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
  namespace: chatbot
  labels:
    app: chatbot
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: chatbot
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: asia.gcr.io/comp7940-group21/pj_chatbot:latest
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

